services:
  db:
    hostname: db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
